"use strict";

const { resolveRuntimeGetter } = require("./MIA_RUNTIME_GETTER");

/**
 * Flatten grouped route-context host bindings for createRouteContextRuntime.
 */

function buildRouteContextCtx(host = {}) {
  const { modules = {}, state = {}, routes = {}, obs = {}, media = {}, koj = {}, core = {} } =
    host;

  return {
    overlayStateModule: modules.overlayStateModule,
    getOverlayState: state.getOverlayState,
    setOverlayState: state.setOverlayState,
    safeRequire: core.safeRequire,
    getPort: state.getPort,
    getObsConnected: state.getObsConnected,
    getObs: state.getObs,
    getDuelState: state.getDuelState,
    setDuelState: state.setDuelState,
    getBackpackState: state.getBackpackState,
    getArenaState: state.getArenaState,
    setArenaState: state.setArenaState,
    platformArenaModule: modules.platformArenaModule,
    getLastGiftMapping: state.getLastGiftMapping,
    getServerStartedAt: core.getServerStartedAt,
    getStreamSession: core.getStreamSession,
    setStreamSession: core.setStreamSession,
    getOutputState: state.getOutputState,
    getKojnozoutState: state.getKojnozoutState,
    setKojnozoutState: state.setKojnozoutState,
    deliveryRuntime: core.deliveryRuntime,
    buildStartupCheckPayload: routes.buildStartupCheckPayload,
    buildHealthPayload: routes.buildHealthPayload,
    buildDiagnosePayload: routes.buildDiagnosePayload,
    ingestAuthGuard: routes.ingestAuthGuard,
    handleIngest: routes.handleIngest,
    handleAudienceIngest: routes.handleAudienceIngest,
    localAdminGuard: routes.localAdminGuard,
    debugRouteGuard: routes.debugRouteGuard,
    buildPublicOverlayStateResponse: routes.buildPublicOverlayStateResponse,
    overlayStateCache: modules.overlayStateCache,
    buildOverlayStateCacheKey: routes.buildOverlayStateCacheKey,
    setOverlay: routes.setOverlay,
    refreshObsMiaBrowserSources: obs.refreshObsMiaBrowserSources,
    executeOverlay: routes.executeOverlay,
    mediaCatalogModule: modules.mediaCatalogModule,
    mediaOrchestratorModule: modules.mediaOrchestratorModule,
    mediaApplyObsModule: modules.mediaApplyObsModule,
    mediaTemplateRendererModule: modules.mediaTemplateRendererModule,
    ensureObsConnectedWithRetry: obs.ensureObsConnectedWithRetry,
    selfRestartModule: modules.selfRestartModule,
    runtimeConfig: core.runtimeConfig,
    videoEngine: media.videoEngine,
    bowlFullVideoModule: media.bowlFullVideoModule,
    safeObsCall: obs.safeObsCall,
    miaEyes: media.miaEyes,
    deliverActionVoice: routes.deliverActionVoice,
    getVoicePlaybackSnapshot: routes.getVoicePlaybackSnapshot,
    speakerRoutingModule: modules.speakerRoutingModule,
    fixObsOverlayBrowserLayouts: obs.fixObsOverlayBrowserLayouts,
    fixObsOverlaySceneTransforms: obs.fixObsOverlaySceneTransforms,
    ensureObsVoiceBrowserReady: obs.ensureObsVoiceBrowserReady,
    auditObsMiaBrowserSources: obs.auditObsMiaBrowserSources,
    ensureObsStreamerCameras: obs.ensureObsStreamerCameras,
    buildObsHealthSnapshot: obs.buildObsHealthSnapshot,
    forceReconnectObs: obs.forceReconnectObs,
    runObsMaintenanceScript: obs.runObsMaintenanceScript,
    obsFixLayoutModule: modules.obsFixLayoutModule,
    buildVisionContext: routes.buildVisionContext,
    immersiveSceneModule: modules.immersiveSceneModule,
    streamerMattingModule: modules.streamerMattingModule,
    obsStreamerCamerasModule: modules.obsStreamerCamerasModule,
    bossMissionModule: modules.bossMissionModule,
    mattingIngestBridge: modules.mattingIngestBridge,
    ensureObsHands: obs.ensureObsHands,
    streamerIdentityModule: modules.streamerIdentityModule,
    writeLog: core.writeLog,
    safeString: core.safeString,
    kojnozoutDuelModule: modules.kojnozoutDuelModule,
    kojnozoutBackpackModule: modules.kojnozoutBackpackModule,
    kojRosterModule: modules.kojRosterModule,
    arenaBattleDemo: modules.arenaBattleDemo,
    scheduleWorldSave: koj.scheduleWorldSave,
    lastDuelSyncSummary: core.lastDuelSyncSummary,
    MIA_SPLIT_OVERLAYS: core.MIA_SPLIT_OVERLAYS,
    overlayStaticDir: core.overlayStaticDir,
    remoteDevModule: modules.remoteDevModule,
    giftMapEnterprise: modules.giftMapEnterprise,
    paintBridge: modules.miaPaintBridge,
    paintWs: modules.miaPaintWs,
    streamSessionModule: core.streamSessionModule,
    buildMiaStatusResponse: routes.buildMiaStatusResponse,
    getSpamSessionEngine: core.getSpamSessionEngine,
    spamSessionEngine: core.spamSessionEngine,
    getStreamState: core.getStreamState,
    serverStartedAt: core.serverStartedAt,
    ecosystemState: core.ecosystemState,
    ttsEngine: core.ttsEngine,
    languageModule: modules.languageModule,
    translateModule: modules.translateModule,
    getInterpreterRuntime: modules.getInterpreterRuntime,
    translationRuntime: modules.translationRuntime,
    deliverMicTranslation: routes.deliverMicTranslation,
    MIA_OVERLAY_BASE: core.MIA_OVERLAY_BASE,
    voiceHoldUntilTs: core.voiceHoldUntilTs,
    mirrorSpeechOverlayFromVoice: routes.mirrorSpeechOverlayFromVoice,
    invalidateOverlayStateCache: routes.invalidateOverlayStateCache,
    runtimeSecurityModule: modules.runtimeSecurityModule,
    handleDebugComment: routes.handleDebugComment,
    handleDebugGift: routes.handleDebugGift,
    processEvent: routes.processEvent,
    applyWorldModeChange: routes.applyWorldModeChange,
    activateComboMoment: routes.activateComboMoment,
    activateBossCinematic: routes.activateBossCinematic,
    capybaraFlowModule: modules.capybaraFlowModule,
    giftVisualComposerModule: modules.giftVisualComposerModule,
    viewerStoryModule: modules.viewerStoryModule,
    storyAnimationEngineModule: modules.storyAnimationEngineModule,
    storyVideoEngineModule: modules.storyVideoEngineModule,
    soloStreamModule: modules.soloStreamModule,
    proactiveHostModule: modules.proactiveHostModule,
    buildSoloStreamSceneCtx: routes.buildSoloStreamSceneCtx,
    voiceLayer: modules.voiceLayer,
    maybeDeliverMiaVoice: routes.maybeDeliverMiaVoice,
    miaEyesModule: modules.miaEyesModule,
    displayVisionModule: modules.displayVisionModule,
    obsVision: modules.obsVision,
    obsVisionModule: modules.obsVisionModule,
    animationEngineModule: modules.animationEngineModule,
    kojTestModeModule: modules.kojTestModeModule,
    kojnozoutVitalsModule: modules.kojnozoutVitalsModule,
    kojnozoutPersistenceModule: modules.kojnozoutPersistenceModule,
    kojnozoutModule: modules.kojnozoutModule,
    streamerShowcaseModule: modules.streamerShowcaseModule,
    speakMiaShowcaseLine: routes.speakMiaShowcaseLine
  };
}

module.exports = { buildRouteContextCtx };
